apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    region: asia-pacific
    room: bj-2
  labels:
    env: staging
    iamId: "0"
  name: test-deploy-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-deploy-2
  template:
    metadata:
      annotations:
        region: asia-pacific
        room: bj-2
      labels:
        app: test-deploy-2
        env: staging
        iamId: "0"
    spec:
      containers:
        - image: ubuntu:latest
          imagePullPolicy: IfNotPresent
          name: main
          command: 
            - /bin/sleep
            - 10d
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            - name: IAM_TREE_ID
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.labels['iamId']
            - name: REGION
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.annotations['region']
            - name: ENV
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.labels['env']
        - image: nginx:alpine
          imagePullPolicy: IfNotPresent
          name: nginx
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            - name: IAM_TREE_ID
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.labels['iamId']
            - name: REGION
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.annotations['region']
            - name: ENV
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.labels['env']