apiVersion: batch/v1
kind: Job
metadata:
  name: app-test-job-dev
  annotations:
    basickube/app-grp: app-test-job
    region: Asia-Pacific
    room: CN-1
  labels:
    basickube/app-grp: app-test-job
    env: dev
    iamId: "0"
    type: job
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1

  ttlSecondsAfterFinished: 0

  template:
    metadata:
      annotations:
        region: Asia-Pacific
        room: CN-1
      labels:
        app: app-test-job-dev
        // controller-uid: 8188c894-1d23-4232-bd9d-89bb20ce4dc9
        env: dev
        iamId: "0"
        type: job
      name: app-test-job-dev
      namespace: default
    spec:
      containers:
      - env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: NODE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: IAM_TREE_ID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['iamId']
        - name: REGION
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.annotations['region']
        image: app-test-img:v1
        imagePullPolicy: IfNotPresent
        name: main
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: OnFailure
      terminationGracePeriodSeconds: 30


